version: "3.0"

services:
    web:
        container_name: ${PROJECT_ID}_web_${PROJECT_REPLICA_NAME}
        image: nginx:latest
        ports:
            - "${PROJECT_PORT_PREFIX}${PROJECT_REPLICA}80:80"
        volumes:
            - ./:/code
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - "php:php"

    php:
        container_name: ${PROJECT_ID}_php_${PROJECT_REPLICA_NAME}
        build: ./.docker/php
        volumes:
            - ./:/code
        links:
            - "mysql:mysql"

    mysql:
        container_name: ${PROJECT_ID}_mysql_${PROJECT_REPLICA_NAME}
        image: mysql:latest
        ports:
            - "${PROJECT_PORT_PREFIX}${PROJECT_REPLICA}06:3306"
        command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp --default-authentication-plugin=mysql_native_password"
        environment:
            MYSQL_DATABASE: ${PROJECT_ID}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

    phpmyadmin:
        container_name: ${PROJECT_ID}_phpmyadmin_${PROJECT_REPLICA_NAME}
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "${PROJECT_PORT_PREFIX}${PROJECT_REPLICA}81:80"
        links:
            - "mysql:mysql"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
